import './globals.css'
import { FaBars, FaSearch, FaUserAlt, FaBell } from "react-icons/fa";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  )
}

function Navbar() {
  return (
    <nav className='backdrop-blur-md py-1 px-2 flex items-center gap-1'>
      <span className='flex-1'>Navbar</span>
          <span className='flex-1'><SearchBox/></span>
          
          
          <span className='flex-1 flex justify-end gap-4 items-center text-xl text-primary'>
            {/* Login Logout Notification Icons */}
          <FaBell />
          <FaUserAlt />
          <FaBars /></span>
    </nav>
  )
}


function SearchBox() {
  return (
  <div className=' bg-secondary2 rounded-full p-1'>
    <form className='flex items-center'>
    <input className='p-1 outline-none bg-secondary2 flex-1 rounded-full rounded-r-none'>
    </input>
    <button type='submit' className='p-1 text-primary rounded-full rounded-l-none'>
      <FaSearch fontSize="1.5em"/>
      </button>
    </form>
  </div>
  )
}
