import './globals.css'
import { FaBars, FaSearch, FaUserAlt, FaBell } from "react-icons/fa";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <nav className='border-solid border-2 border-red-500 py-2 flex'>
          <span className='flex-1'>Navbar</span>
          <span className='flex-1'><SearchBox/></span>
          <span className='flex-1'>Login Logout Notification Icons
          <FaBell />
          <FaUserAlt />
          <FaBars /></span>
          </nav>
        {children}
      </body>
    </html>
  )
}


function SearchBox() {
  return (
  <div className='border-solid border-2 border-green-500 rounded-lg'>
    <form>
    <input className='border-solid border-2 border-yellow-500 rounded-lg'>
    </input>
    <button type='submit' className='border-solid border-2 border-yellow-500 rounded-lg'><FaSearch color='red' fontSize="1.5em"/></button>
    </form>
  </div>
  )
}
