import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  // const {data, isFetching, isError} = api.posts.createPost.useMutation({});
  // console.log(data, isFetching, isError);
  const [state1, setState1] = useState();
  const mutator = api.posts.createPost.useMutation();
  console.log(mutator);

  

useEffect(() => {
  (async () => {
    const resp = await mutator.mutate({message: 'xx', uname: 'hu_tao', privacy: 1});
    console.log(resp);
  })();
}, [])


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <div>Index</div>
      </main>
    </>
  );
};

export default Home;

